-- V1__init.sql — Initial schema for The-Dogs
-- All timestamps are stored WITH TIME ZONE.
-- UUIDs are generated by the application layer (JPA @GeneratedValue(UUID)).

-- ─────────────────────────────────────────────────────────────────────────────
-- Users (trainers)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE users (
    id          UUID                        NOT NULL DEFAULT gen_random_uuid(),
    email       VARCHAR(255)                NOT NULL,
    password_hash VARCHAR(255)              NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE,
    updated_at  TIMESTAMP WITH TIME ZONE,

    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE INDEX idx_users_email ON users (email);

-- ─────────────────────────────────────────────────────────────────────────────
-- User roles (replaces roles text[] for JPA @ElementCollection compatibility)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE user_roles (
    user_id UUID        NOT NULL,
    role    VARCHAR(50) NOT NULL,

    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_user_roles_user_id ON user_roles (user_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- Clients
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE clients (
    id          UUID                        NOT NULL DEFAULT gen_random_uuid(),
    trainer_id  UUID                        NOT NULL,
    name        VARCHAR(255)                NOT NULL,
    phone       VARCHAR(50),
    email       VARCHAR(255),
    notes       TEXT,
    created_at  TIMESTAMP WITH TIME ZONE,
    updated_at  TIMESTAMP WITH TIME ZONE,

    CONSTRAINT pk_clients PRIMARY KEY (id),
    CONSTRAINT fk_clients_trainer FOREIGN KEY (trainer_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_clients_trainer_id ON clients (trainer_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- Dogs
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE dogs (
    id          UUID                        NOT NULL DEFAULT gen_random_uuid(),
    client_id   UUID                        NOT NULL,
    name        VARCHAR(255)                NOT NULL,
    breed       VARCHAR(255),
    birthdate   DATE,
    sex         VARCHAR(10),
    metadata    JSONB,
    archived    BOOLEAN                     NOT NULL DEFAULT false,
    created_at  TIMESTAMP WITH TIME ZONE,
    updated_at  TIMESTAMP WITH TIME ZONE,

    CONSTRAINT pk_dogs PRIMARY KEY (id),
    CONSTRAINT fk_dogs_client FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE CASCADE
);

CREATE INDEX idx_dogs_client_id ON dogs (client_id);
CREATE INDEX idx_dogs_archived  ON dogs (archived) WHERE archived = false;

-- ─────────────────────────────────────────────────────────────────────────────
-- Notes (scoped per dog)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE notes (
    id          UUID                        NOT NULL DEFAULT gen_random_uuid(),
    dog_id      UUID                        NOT NULL,
    trainer_id  UUID                        NOT NULL,
    title       VARCHAR(255)                NOT NULL,
    body        TEXT                        NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE,
    updated_at  TIMESTAMP WITH TIME ZONE,

    CONSTRAINT pk_notes PRIMARY KEY (id),
    CONSTRAINT fk_notes_dog     FOREIGN KEY (dog_id)     REFERENCES dogs  (id) ON DELETE CASCADE,
    CONSTRAINT fk_notes_trainer FOREIGN KEY (trainer_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_notes_dog_id     ON notes (dog_id);
CREATE INDEX idx_notes_trainer_id ON notes (trainer_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- Appointments
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE appointments (
    id          UUID                        NOT NULL DEFAULT gen_random_uuid(),
    trainer_id  UUID                        NOT NULL,
    client_id   UUID                        NOT NULL,
    starts_at   TIMESTAMP WITH TIME ZONE    NOT NULL,
    ends_at     TIMESTAMP WITH TIME ZONE    NOT NULL,
    location    VARCHAR(255),
    status      VARCHAR(50)                 NOT NULL DEFAULT 'SCHEDULED',
    notes       TEXT,
    created_at  TIMESTAMP WITH TIME ZONE,
    updated_at  TIMESTAMP WITH TIME ZONE,

    CONSTRAINT pk_appointments  PRIMARY KEY (id),
    CONSTRAINT fk_appt_trainer  FOREIGN KEY (trainer_id) REFERENCES users   (id) ON DELETE CASCADE,
    CONSTRAINT fk_appt_client   FOREIGN KEY (client_id)  REFERENCES clients (id) ON DELETE CASCADE
);

CREATE INDEX idx_appointments_trainer_id ON appointments (trainer_id);
CREATE INDEX idx_appointments_client_id  ON appointments (client_id);
CREATE INDEX idx_appointments_starts_at  ON appointments (starts_at);
