package com.thedogs.modules.auth;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;
import java.util.UUID;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * AUTH-03: Persisted refresh token row.
 *
 * <p>The token value sent to the client is 256 random bits, base64url-encoded (no padding). Only
 * the SHA-256 hash of the raw bytes is stored here; the cleartext value is never persisted (AC-10).
 *
 * <p>family_id groups all tokens issued from a single login session. On theft detection (a used
 * token is presented again) the entire family is revoked, invalidating all concurrently-active
 * sessions derived from that original login.
 */
@Entity
@Table(name = "refresh_token")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString(onlyExplicitlyIncluded = true)
public class RefreshToken {

  /** Application-assigned UUID — not generated by the DB to allow deterministic test fixtures. */
  @Id
  @ToString.Include
  private UUID id;

  /** Groups all rotation-chain tokens from a single login session. */
  @Column(name = "family_id", nullable = false)
  private UUID familyId;

  /** UUID of the token this token was rotated from; null for the initial login token. */
  @Column(name = "parent_id")
  private UUID parentId;

  @Column(name = "user_id", nullable = false)
  @ToString.Include
  private UUID userId;

  /**
   * SHA-256 hex of the raw 32-byte random value sent to the client. Never log this field (AC-10).
   * Excluded from @ToString to prevent accidental logging.
   */
  @Column(name = "token_hash", nullable = false, length = 64, unique = true)
  private String tokenHash;

  @Column(name = "issued_at", nullable = false)
  private Instant issuedAt;

  @Column(name = "expires_at", nullable = false)
  private Instant expiresAt;

  /** Set when this token has been rotated (used to issue a new one). Null = still rotatable. */
  @Column(name = "used_at")
  private Instant usedAt;

  /** Set when this token (or its family) was explicitly revoked (logout or theft detection). */
  @Column(name = "revoked_at")
  private Instant revokedAt;

  @Column(name = "user_agent")
  private String userAgent;

  /**
   * Coarse IP bucket (e.g., first two octets of IPv4) for anomaly logging without storing PII.
   */
  @Column(name = "ip_bucket")
  private String ipBucket;

  // equals/hashCode based on the stable business key (token_hash is globally unique)
  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (!(o instanceof RefreshToken other)) return false;
    return tokenHash != null && tokenHash.equals(other.tokenHash);
  }

  @Override
  public int hashCode() {
    return tokenHash == null ? 0 : tokenHash.hashCode();
  }
}
